incorporating ovs-docker-remote

diff --git a/utilities/ovs-docker-remote b/utilities/ovs-docker-remote
--- a/utilities/ovs-docker-remote
+++ b/utilities/ovs-docker-remote
@@ -1,5 +1,19 @@
 #!/bin/bash
 
+search_path () {
+    save_IFS=$IFS
+    IFS=:
+    for dir in $PATH; do
+        IFS=$save_IFS
+	if test -x "$dir/$1"; then
+            return 0
+	fi
+    done
+    IFS=$save_IFS
+    echo >&2 "$0: $1 not found in \$PATH, please install and try again"
+    exit 1
+}
+
 add_port () {
          BRIDGE="$1"
          INTERFACE="$2"
@@ -69,7 +83,6 @@ add_port () {
         # Add one end of veth to OVS bridge                 
         if sudo ovs-vsctl --db=tcp:$IP:$OVS_PORT --may-exist add-port "$BRIDGE" "br-${NET_ID}" -- set interface "br-${NET_ID}" external_ids:container_id="$CONTAINER" external_ids:container_iface="$INTERFACE"; then :; else
             echo "Failed to add br-""${NET_ID}"" port to bridge $BRIDGE"
-            #ssh $USERNAME@$IP sudo ip link delete "${PORTNAME}_l"
 	    curl -s -X DELETE http://$IP:$DOCKER_PORT/v1.37/networks/$NET_ID
             exit 1
 	fi
@@ -141,29 +154,41 @@ del_ports () {
           done
 }
 
-search_path () {
-    save_IFS=$IFS
-    IFS=:
-    for dir in $PATH; do
-        IFS=$save_IFS
-	if test -x "$dir/$1"; then
-            return 0
-	fi
-    done
-    IFS=$save_IFS
-    echo >&2 "$0: $1 not found in \$PATH, please install and try again"
-    exit 1
+usage() {
+    cat << EOF
+${UTIL}: Performs integration of Open vSwitch with Docker on remote machines. 
+usage: ${UTIL} COMMAND
+
+Commands:
+  add-port BRIDGE INTERFACE CONTAINER REMOTE_IP OVS_PORT DOCKER_PORT 
+  	   	    [--ipaddress="ADDRESS"] [--gateway=GATEWAY] 
+		    [--macaddress="MACADDRESS"] [--mtu=MTU]
+Adds INTERFACE inside CONTAINER and connects it as a port
+                    in Open vSwitch BRIDGE. Optionally, sets ADDRESS on
+                    INTERFACE. ADDRESS can include a '/' to represent network
+                    prefix length. Optionally, sets a GATEWAY, MACADDRESS
+                    and MTU.  e.g.:
+                    ${UTIL} add-port br-int eth1 c474a0e2830e 128.28.32.6 6677 4243
+                    --ipaddress=192.168.1.2/24 --gateway=192.168.1.1
+                    --macaddress="a2:c3:0d:49:7f:f8" --mtu=1450
+  del-port BRIDGE INTERFACE CONTAINER REMOTE_IP OVS_PORT DOCKER_PORT
+                    Deletes INTERFACE inside CONTAINER and removes its
+                    connection to Open vSwitch BRIDGE. e.g.:
+                    ${UTIL} del-port br-int eth1 c474a0e2830e 128.28.32.6 6677 4243
+  del-ports BRIDGE CONTAINER REMOTE_IP OVS_PORT DOCKER_PORT
+                    Removes all Open vSwitch interfaces from CONTAINER. e.g.:
+                    ${UTIL} del-ports br-int c474a0e2830e 128.28.32.6 6677 4243
+Options:
+  -h, --help        display this help message.
+EOF
 }
+
 
 UTIL=$(basename $0)
 search_path ovs-vsctl
 search_path uuidgen
 search_path jq
-
-if (ip netns) > /dev/null 2>&1; then :; else
-   echo >&2 "$UTIL: ip utility not found (or it does not support netns), cannot proceed"
-   exit 1
-fi
+search_path curl
 
 if [ $# -eq 0 ]; then
    exit 0
